type: object
properties:
  id:
    type: string
  name:
    type: string
  brand:
    type: string
  price:
    type: number
    format: dobule
  stock:
    type: number
  categories:
    type: array
    items:
      $ref: './CategoryInfoDTO.yaml'
